name: WIP Action
description: Sets a PR status to pending if it finds specified terms in the pull request title, label or commit message.
author: bubkoo <bubkoo.wy@gmail.com>

inputs:
  GITHUB_TOKEN:
    required: true
    description: Your GitHub token for authentication.
  CONFIG_FILE:
    description: Config file path relative to your repo's root.
    required: false

runs:
  using: node12
  main: dist/index.js

branding:
  icon: alert-triangle
  color: yellow
